LOADER_TYPE=$1
LOAD_MODEL=$2
cd ../

python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_1.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_1.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_3.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_3.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_5.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_5.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_6.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_6.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_7.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_7.txt,epochs=1" --background

python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "z_test_channel=True,sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_brightness_4.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_brightness_4.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "z_test_channel=True,sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_brightness_5.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_brightness_5.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_brightness_6.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_brightness_6.txt,epochs=1" --background
python main.py --config configs/ev_tta.ini --exp_name tent_exp --override "sentry_inconsistent_fill=0.0,uda_loss=sentry_mod_jensen_consistent,loader_type=${LOADER_TYPE:-"reshape_then_acc_time_pol"},load_model=${LOAD_MODEL:-"./experiments/pretrained/2_time_surface/best.tar"},train_file=./Datasets/N_Imagenet_cam/val_mode_brightness_7.txt,epochs=1,val_file=./Datasets/N_Imagenet_cam/val_mode_brightness_7.txt,epochs=1" --background
